export default [
    {
        "id": 278,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
        "genres": "Drama, Crime",
        "language": "English",
        "title": "The Shawshank Redemption",
        "overview": "Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
        "releaseDate": "1994-09-23",
        "popularity": 33.0665,
        "voteAverage": 8.71,
        "voteCount": 28249
    },
    {
        "id": 238,
        "isAdult": false,
        "backdropImage": "/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
        "genres": "Drama, Crime",
        "language": "English",
        "title": "The Godfather",
        "overview": "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
        "releaseDate": "1972-03-14",
        "popularity": 50.204,
        "voteAverage": 8.7,
        "voteCount": 21412
    },
    {
        "id": 240,
        "isAdult": false,
        "backdropImage": "/kGzFbGhp99zva6oZODW5atUtnqi.jpg",
        "genres": "Drama, Crime",
        "language": "English",
        "title": "The Godfather Part II",
        "overview": "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
        "releaseDate": "1974-12-20",
        "popularity": 16.593,
        "voteAverage": 8.6,
        "voteCount": 12934
    },
    {
        "id": 424,
        "isAdult": false,
        "backdropImage": "/zb6fM1CX41D9rF9hdgclu0peUmy.jpg",
        "genres": "Drama, History, War",
        "language": "English",
        "title": "Schindler's List",
        "overview": "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
        "releaseDate": "1993-12-15",
        "popularity": 18.3518,
        "voteAverage": 8.565,
        "voteCount": 16412
    },
    {
        "id": 389,
        "isAdult": false,
        "backdropImage": "/bxgTSUenZDHNFerQ1whRKplrMKF.jpg",
        "genres": "Drama",
        "language": "English",
        "title": "12 Angry Men",
        "overview": "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg",
        "releaseDate": "1957-04-10",
        "popularity": 24.4255,
        "voteAverage": 8.548,
        "voteCount": 9110
    },
    {
        "id": 129,
        "isAdult": false,
        "backdropImage": "/6oaL4DP75yABrd5EbC4H2zq5ghc.jpg",
        "genres": "Animation, Family, Fantasy",
        "language": "Japanese",
        "title": "千と千尋の神隠し",
        "overview": "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
        "releaseDate": "2001-07-20",
        "popularity": 24.0763,
        "voteAverage": 8.536,
        "voteCount": 17113
    },
    {
        "id": 155,
        "isAdult": false,
        "backdropImage": "/oOv2oUXcAaNXakRqUPxYq5lJURz.jpg",
        "genres": "Drama, Action, Crime, Thriller",
        "language": "English",
        "title": "The Dark Knight",
        "overview": "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
        "releaseDate": "2008-07-16",
        "popularity": 28.0113,
        "voteAverage": 8.52,
        "voteCount": 33804
    },
    {
        "id": 19404,
        "isAdult": false,
        "backdropImage": "/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg",
        "genres": "Comedy, Drama, Romance",
        "language": "Hindi",
        "title": "दिलवाले दुल्हनिया ले जायेंगे",
        "overview": "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/rfcy6Gd3PbFIqwZX5U8xnbv7jOc.jpg",
        "releaseDate": "1995-10-20",
        "popularity": 6.3222,
        "voteAverage": 8.5,
        "voteCount": 4484
    },
    {
        "id": 497,
        "isAdult": false,
        "backdropImage": "/amZavErrjrdgDwhsIdpWxHNenIx.jpg",
        "genres": "Fantasy, Drama, Crime",
        "language": "English",
        "title": "The Green Mile",
        "overview": "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg",
        "releaseDate": "1999-12-10",
        "popularity": 17.3203,
        "voteAverage": 8.5,
        "voteCount": 18065
    },
    {
        "id": 496243,
        "isAdult": false,
        "backdropImage": "/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg",
        "genres": "Comedy, Thriller, Drama",
        "language": "Korean",
        "title": "기생충",
        "overview": "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
        "releaseDate": "2019-05-30",
        "popularity": 66.4824,
        "voteAverage": 8.5,
        "voteCount": 19010
    },
    {
        "id": 680,
        "isAdult": false,
        "backdropImage": "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
        "genres": "Thriller, Crime",
        "language": "English",
        "title": "Pulp Fiction",
        "overview": "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg",
        "releaseDate": "1994-09-10",
        "popularity": 18.5855,
        "voteAverage": 8.49,
        "voteCount": 28634
    },
    {
        "id": 372058,
        "isAdult": false,
        "backdropImage": "/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg",
        "genres": "Animation, Romance, Drama",
        "language": "Japanese",
        "title": "君の名は。",
        "overview": "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/8GJsy7w7frGquw1cy9jasOGNNI1.jpg",
        "releaseDate": "2016-08-26",
        "popularity": 46.3229,
        "voteAverage": 8.484,
        "voteCount": 11748
    },
    {
        "id": 122,
        "isAdult": false,
        "backdropImage": "/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg",
        "genres": "Adventure, Fantasy, Action",
        "language": "English",
        "title": "The Lord of the Rings: The Return of the King",
        "overview": "As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.​",
        "posterPath": "https://image.tmdb.org/t/p/w1280/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
        "releaseDate": "2003-12-17",
        "popularity": 22.1348,
        "voteAverage": 8.483,
        "voteCount": 25038
    },
    {
        "id": 13,
        "isAdult": false,
        "backdropImage": "/ghgfzbEV7kbpbi1O8eIILKVXEA8.jpg",
        "genres": "Comedy, Drama, Romance",
        "language": "English",
        "title": "Forrest Gump",
        "overview": "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
        "releaseDate": "1994-06-23",
        "popularity": 23.1535,
        "voteAverage": 8.468,
        "voteCount": 28182
    },
    {
        "id": 429,
        "isAdult": false,
        "backdropImage": "/x4biAVdPVCghBlsVIzB6NmbghIz.jpg",
        "genres": "Western",
        "language": "Italian",
        "title": "Il buono, il brutto, il cattivo",
        "overview": "While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg",
        "releaseDate": "1966-12-22",
        "popularity": 15.1409,
        "voteAverage": 8.462,
        "voteCount": 8968
    },
    {
        "id": 346,
        "isAdult": false,
        "backdropImage": "/sJNNMCc6B7KZIY3LH3JMYJJNH5j.jpg",
        "genres": "Action, Drama",
        "language": "Japanese",
        "title": "七人の侍",
        "overview": "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg",
        "releaseDate": "1954-04-26",
        "popularity": 6.7294,
        "voteAverage": 8.457,
        "voteCount": 3883
    },
    {
        "id": 769,
        "isAdult": false,
        "backdropImage": "/7TF4p86ZafnxFuNqWdhpHXFO244.jpg",
        "genres": "Drama, Crime",
        "language": "English",
        "title": "GoodFellas",
        "overview": "The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
        "releaseDate": "1990-09-12",
        "popularity": 62.7547,
        "voteAverage": 8.456,
        "voteCount": 13346
    },
    {
        "id": 157336,
        "isAdult": false,
        "backdropImage": "/l33oR0mnvf20avWyIMxW02EtQxn.jpg",
        "genres": "Adventure, Drama, Science Fiction",
        "language": "English",
        "title": "Interstellar",
        "overview": "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
        "releaseDate": "2014-11-05",
        "popularity": 38.4072,
        "voteAverage": 8.455,
        "voteCount": 37076
    },
    {
        "id": 12477,
        "isAdult": false,
        "backdropImage": "/tDFvXn4tane9lUvFAFAUkMylwSr.jpg",
        "genres": "Animation, Drama, War",
        "language": "Japanese",
        "title": "火垂るの墓",
        "overview": "In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg",
        "releaseDate": "1988-04-16",
        "popularity": 0.0083,
        "voteAverage": 8.451,
        "voteCount": 5870
    },
    {
        "id": 637,
        "isAdult": false,
        "backdropImage": "/6aNKD81RHR1DqUUa8kOZ1TBY1Lp.jpg",
        "genres": "Comedy, Drama",
        "language": "Italian",
        "title": "La vita è bella",
        "overview": "A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/74hLDKjD5aGYOotO6esUVaeISa2.jpg",
        "releaseDate": "1997-12-20",
        "popularity": 10.82,
        "voteAverage": 8.448,
        "voteCount": 13355
    },
    {
        "id": 550,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/hZkgoQYus5vegHoetLkCJzb17zJ.jpg",
        "genres": "Drama",
        "language": "English",
        "title": "Fight Club",
        "overview": "A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground \"fight clubs\" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
        "releaseDate": "1999-10-15",
        "popularity": 24.716,
        "voteAverage": 8.438,
        "voteCount": 30232
    },
    {
        "id": 11216,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/zoVeIgKzGJzpdG6Gwnr7iOYfIMU.jpg",
        "genres": "Drama, Romance",
        "language": "Italian",
        "title": "Nuovo Cinema Paradiso",
        "overview": "A filmmaker recalls his childhood, when he fell in love with the movies at his village's theater and formed a deep friendship with the theater's projectionist.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/gCI2AeMV4IHSewhJkzsur5MEp6R.jpg",
        "releaseDate": "1988-11-17",
        "popularity": 6.9899,
        "voteAverage": 8.4,
        "voteCount": 4519
    },
    {
        "id": 598,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/uvitbjFU4JqvMwIkMWHp69bmUzG.jpg",
        "genres": "Drama, Crime",
        "language": "Portuguese",
        "title": "Cidade de Deus",
        "overview": "In the poverty-stricken favelas of Rio de Janeiro in the 1970s, two young men choose different paths. Rocket is a budding photographer who documents the increasing drug-related violence of his neighborhood, while José “Zé” Pequeno is an ambitious drug dealer diving into a dangerous life of crime.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/k7eYdWvhYQyRQoU2TB2A2Xu2TfD.jpg",
        "releaseDate": "2002-08-30",
        "popularity": 9.1715,
        "voteAverage": 8.428,
        "voteCount": 7625
    },
    {
        "id": 40096,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/alQqTpmEkxSLgajfEYTsTH6nAKB.jpg",
        "genres": "Comedy, Drama, Fantasy",
        "language": "Portuguese",
        "title": "O Auto da Compadecida",
        "overview": "The lively João Grilo and the sly Chicó are poor guys living in the hinterland who cheat a bunch of people in a small town in Northeastern Brazil. When they die, they have to be judged by Christ, the Devil and the Virgin Mary before they are admitted to paradise.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/aovknfdLnFp1IiWi3yvTAg8Gm5k.jpg",
        "releaseDate": "2000-09-15",
        "popularity": 1.9499,
        "voteAverage": 8.423,
        "voteCount": 1156
    },
    {
        "id": 539,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/uif5fUshJrXyyDzfpzp1DLw3N0S.jpg",
        "genres": "Horror, Thriller, Mystery",
        "language": "English",
        "title": "Psycho",
        "overview": "When larcenous real estate clerk Marion Crane goes on the lam with a wad of cash and hopes of starting a new life, she ends up at the notorious Bates Motel, where manager Norman Bates cares for his housebound mother.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/yz4QVqPx3h1hD1DfqqQkCq3rmxW.jpg",
        "releaseDate": "1960-06-22",
        "popularity": 8.7,
        "voteAverage": 8.423,
        "voteCount": 10339
    },
    {
        "id": 120,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/x2RS3uTcsJJ9IfjNPcgDmukoEcQ.jpg",
        "genres": "Adventure, Fantasy, Action",
        "language": "English",
        "title": "The Lord of the Rings: The Fellowship of the Ring",
        "overview": "Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator. Along the way, a fellowship is formed to protect the ringbearer and make sure that the ring arrives at its final destination: Mt. Doom, the only place where it can be destroyed.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
        "releaseDate": "2001-12-18",
        "popularity": 24.1156,
        "voteAverage": 8.42,
        "voteCount": 25936
    },
    {
        "id": 14537,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/nC3IjYhUgZWgfKfFX0ygMigFwgc.jpg",
        "genres": "Action, Drama, History",
        "language": "Japanese",
        "title": "切腹",
        "overview": "Down-on-his-luck veteran Tsugumo Hanshirō enters the courtyard of the prosperous House of Iyi. Unemployed, and with no family, he hopes to find a place to commit seppuku—and a worthy second to deliver the coup de grâce in his suicide ritual. The senior counselor for the Iyi clan questions the ronin’s resolve and integrity, suspecting Hanshirō of seeking charity rather than an honorable end. What follows is a pair of interlocking stories which lay bare the difference between honor and respect, and promises to examine the legendary foundations of the Samurai code.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/5konZnIbcAxZjP616Cz5o9bKEfW.jpg",
        "releaseDate": "1962-09-15",
        "popularity": 3.7304,
        "voteAverage": 8.4,
        "voteCount": 1070
    },
    {
        "id": 667257,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/bxSBOAD8AuMHYMdW3jso9npAkgt.jpg",
        "genres": "Family, Drama",
        "language": "Spanish",
        "title": "Cosas imposibles",
        "overview": "After the death of her abusive husband, Matilde finds her new best friend in Miguel, her young, insecure, and disoriented neighbor.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/t2Ew8NZ8Ci2kqmoecZUNQUFDJnQ.jpg",
        "releaseDate": "2021-06-17",
        "popularity": 1.4731,
        "voteAverage": 8.4,
        "voteCount": 403
    },
    {
        "id": 510,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/qUq3QTr2KLvGIcN0GaaaYx9bbyH.jpg",
        "genres": "Drama",
        "language": "English",
        "title": "One Flew Over the Cuckoo's Nest",
        "overview": "A petty criminal fakes insanity to serve his sentence in a mental ward rather than prison. He soon finds himself as a leader to the other patients—and an enemy to the cruel, domineering nurse who runs the ward.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/kjWsMh72V6d8KRLV4EOoSJLT1H7.jpg",
        "releaseDate": "1975-11-19",
        "popularity": 8.7623,
        "voteAverage": 8.413,
        "voteCount": 10751
    },
    {
        "id": 696374,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/w2uGvCpMtvRqZg6waC1hvLyZoJa.jpg",
        "genres": "Romance, Drama",
        "language": "English",
        "title": "Gabriel's Inferno",
        "overview": "An intriguing and sinful exploration of seduction, forbidden love, and redemption, Gabriel's Inferno is a captivating and wildly passionate tale of one man's escape from his own personal hell as he tries to earn the impossible--forgiveness and love.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/yXRoyYzIo17HfANn07oXYdyBy4h.jpg",
        "releaseDate": "2020-05-29",
        "popularity": 3.1128,
        "voteAverage": 8.4,
        "voteCount": 2419
    },
    {
        "id": 311,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/uPYa165sraN2c8gZBM9C47g3JoU.jpg",
        "genres": "Drama, Crime",
        "language": "English",
        "title": "Once Upon a Time in America",
        "overview": "A former Prohibition-era Jewish gangster returns to the Lower East Side of Manhattan over thirty years later, where he once again must confront the ghosts and regrets of his old life.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/i0enkzsL5dPeneWnjl1fCWm6L7k.jpg",
        "releaseDate": "1984-05-23",
        "popularity": 8.731,
        "voteAverage": 8.407,
        "voteCount": 5601
    },
    {
        "id": 121,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/jfEOzpsjc6JDlKhUHb4toWQPt.jpg",
        "genres": "Adventure, Fantasy, Action",
        "language": "English",
        "title": "The Lord of the Rings: The Two Towers",
        "overview": "Frodo Baggins and the other members of the Fellowship continue on their sacred quest to destroy the One Ring--but on separate paths. Their destinies lie at two towers--Orthanc Tower in Isengard, where the corrupt wizard Saruman awaits, and Sauron's fortress at Barad-dur, deep within the dark lands of Mordor. Frodo and Sam are trekking to Mordor to destroy the One Ring of Power while Gimli, Legolas and Aragorn search for the orc-captured Merry and Pippin. All along, nefarious wizard Saruman awaits the Fellowship members at the Orthanc Tower in Isengard.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg",
        "releaseDate": "2002-12-18",
        "popularity": 16.658,
        "voteAverage": 8.404,
        "voteCount": 22542
    },
    {
        "id": 255709,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/4Nx40jwpoTHPjCWNGoaZ6kaoGxa.jpg",
        "genres": "Drama",
        "language": "Korean",
        "title": "소원",
        "overview": "After 8-year-old So-won narrowly survives a brutal sexual assault, her family labors to help her heal while coping with their own rage and grief.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/x9yjkm9gIz5qI5fJMUTfBnWiB2o.jpg",
        "releaseDate": "2013-10-02",
        "popularity": 3.6816,
        "voteAverage": 8.4,
        "voteCount": 774
    },
    {
        "id": 324857,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/8mnXR9rey5uQ08rZAvzojKWbDQS.jpg",
        "genres": "Animation, Action, Adventure, Science Fiction",
        "language": "English",
        "title": "Spider-Man: Into the Spider-Verse",
        "overview": "Struggling to find his place in the world while juggling school and family, Brooklyn teenager Miles Morales is unexpectedly bitten by a radioactive spider and develops unfathomable powers just like the one and only Spider-Man. While wrestling with the implications of his new abilities, Miles discovers a super collider created by the madman Wilson \"Kingpin\" Fisk, causing others from across the Spider-Verse to be inadvertently transported to his dimension.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
        "releaseDate": "2018-12-06",
        "popularity": 17.4339,
        "voteAverage": 8.397,
        "voteCount": 16105
    },
    {
        "id": 4935,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/nv5wwZou159v5OC61i4ElR7OqyY.jpg",
        "genres": "Fantasy, Animation, Adventure",
        "language": "Japanese",
        "title": "ハウルの動く城",
        "overview": "Sophie, a young milliner, is turned into an elderly woman by a witch who enters her shop and curses her. She encounters a wizard named Howl and gets caught up in his resistance to fighting for the king.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/23hUJh7JdO23SpgUB5oiFDQk2wX.jpg",
        "releaseDate": "2004-09-09",
        "popularity": 14.8971,
        "voteAverage": 8.397,
        "voteCount": 10281
    },
    {
        "id": 1891,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/dMZxEdrWIzUmUoOz2zvmFuutbj7.jpg",
        "genres": "Adventure, Action, Science Fiction",
        "language": "English",
        "title": "The Empire Strikes Back",
        "overview": "The epic saga continues as Luke Skywalker, in hopes of defeating the evil Galactic Empire, learns the ways of the Jedi from aging master Yoda. But Darth Vader is more determined than ever to capture Luke. Meanwhile, rebel leader Princess Leia, cocky Han Solo, Chewbacca, and droids C-3PO and R2-D2 are thrown into various stages of capture, betrayal and despair.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/nNAeTmF4CtdSgMDplXTDPOpYzsX.jpg",
        "releaseDate": "1980-05-20",
        "popularity": 12.3146,
        "voteAverage": 8.393,
        "voteCount": 17375
    },
    {
        "id": 378064,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/5lAMQMWpXMsirvtLLvW7cJgEPkU.jpg",
        "genres": "Animation, Drama, Romance",
        "language": "Japanese",
        "title": "映画 聲の形",
        "overview": "Shouya Ishida starts bullying the new girl in class, Shouko Nishimiya, because she is deaf. But as the teasing continues, the rest of the class starts to turn on Shouya for his lack of compassion. When they leave elementary school, Shouko and Shouya do not speak to each other again... until an older, wiser Shouya, tormented by his past behaviour, decides he must see Shouko once more. He wants to atone for his sins, but is it already too late...?",
        "posterPath": "https://image.tmdb.org/t/p/w1280/tuFaWiqX0TXoWu7DGNcmX3UW7sT.jpg",
        "releaseDate": "2016-09-17",
        "popularity": 9.6955,
        "voteAverage": 8.4,
        "voteCount": 4109
    },
    {
        "id": 724089,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/jtAI6OJIWLWiRItNSZoWjrsUtmi.jpg",
        "genres": "Romance, Drama",
        "language": "English",
        "title": "Gabriel's Inferno: Part II",
        "overview": "Professor Gabriel Emerson finally learns the truth about Julia Mitchell's identity, but his realization comes a moment too late. Julia is done waiting for the well-respected Dante specialist to remember her and wants nothing more to do with him. Can Gabriel win back her heart before she finds love in another's arms?",
        "posterPath": "https://image.tmdb.org/t/p/w1280/x5o8cLZfEXMoZczTYWLrUo1P7UJ.jpg",
        "releaseDate": "2020-07-31",
        "popularity": 1.4645,
        "voteAverage": 8.4,
        "voteCount": 1521
    },
    {
        "id": 423,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/dVr11o9or7AS8AMPfwjSpEU83iU.jpg",
        "genres": "Drama, War",
        "language": "English",
        "title": "The Pianist",
        "overview": "The true story of pianist Władysław Szpilman's experiences in Warsaw during the Nazi occupation. When the Jews of the city find themselves forced into a ghetto, Szpilman finds work playing in a café; and when his family is deported in 1942, he stays behind, works for a while as a laborer, and eventually goes into hiding in the ruins of the war-torn city.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg",
        "releaseDate": "2002-09-17",
        "popularity": 14.2692,
        "voteAverage": 8.379,
        "voteCount": 9500
    },
    {
        "id": 704264,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/uBZQOYZLIU9dBmd62fdzBAoropu.jpg",
        "genres": "Action, Adventure, Animation, Drama",
        "language": "English",
        "title": "Primal: Tales of Savagery",
        "overview": "Genndy Tartakovsky's Primal: Tales of Savagery features a caveman and a dinosaur on the brink of extinction. Bonded by tragedy, this unlikely friendship becomes the only hope of survival.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/9NBBkdxH0TjQEBSN2AzeE1sgsF9.jpg",
        "releaseDate": "2019-11-21",
        "popularity": 1.6169,
        "voteAverage": 8.378,
        "voteCount": 332
    },
    {
        "id": 761053,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/fQq1FWp1rC89xDrRMuyFJdFUdMd.jpg",
        "genres": "Romance, Drama",
        "language": "English",
        "title": "Gabriel's Inferno: Part III",
        "overview": "The final part of the film adaption of the erotic romance novel Gabriel's Inferno written by an anonymous Canadian author under the pen name Sylvain Reynard.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/fYtHxTxlhzD4QWfEbrC1rypysSD.jpg",
        "releaseDate": "2020-11-19",
        "popularity": 2.8434,
        "voteAverage": 8.376,
        "voteCount": 1058
    },
    {
        "id": 244786,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/fRGxZuo7jJUWQsVg9PREb98Aclp.jpg",
        "genres": "Drama, Music",
        "language": "English",
        "title": "Whiplash",
        "overview": "Under the direction of a ruthless instructor, a talented young drummer begins to pursue perfection at any cost, even his humanity.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
        "releaseDate": "2014-10-10",
        "popularity": 17.9407,
        "voteAverage": 8.376,
        "voteCount": 15610
    },
    {
        "id": 807,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/p1PLSI5Nw2krGxD7X4ulul1tDAk.jpg",
        "genres": "Crime, Mystery, Thriller",
        "language": "English",
        "title": "Se7en",
        "overview": "Two homicide detectives are on a desperate hunt for a serial killer whose crimes are based on the \"seven deadly sins\" in this dark and haunting film that takes viewers from the tortured remains of one victim to the next. The seasoned Det. Somerset researches each sin in an effort to get inside the killer's mind, while his novice partner, Mills, scoffs at his efforts to unravel the case.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/191nKfP0ehp3uIvWqgPbFmI4lv9.jpg",
        "releaseDate": "1995-09-22",
        "popularity": 19.2649,
        "voteAverage": 8.375,
        "voteCount": 21689
    },
    {
        "id": 1058694,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/gutU32BiBxJvJdzLv5RWC9hQhNh.jpg",
        "genres": "Drama",
        "language": "Spanish",
        "title": "Radical",
        "overview": "In a Mexican border town plagued by neglect, corruption, and violence, a frustrated teacher tries an unorthodox new method to break through his students’ apathy and unlock their curiosity, their potential... and perhaps even their genius.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/eGMkkbG85JUyXQEsbZKSnBrymts.jpg",
        "releaseDate": "2023-10-19",
        "popularity": 3.1144,
        "voteAverage": 8.4,
        "voteCount": 450
    },
    {
        "id": 27205,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
        "genres": "Action, Science Fiction, Adventure",
        "language": "English",
        "title": "Inception",
        "overview": "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: \"inception\", the implantation of another person's idea into a target's subconscious.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/ljsZTbVsrQSqZgWeep2B1QiDKuh.jpg",
        "releaseDate": "2010-07-15",
        "popularity": 26.2481,
        "voteAverage": 8.368,
        "voteCount": 37435
    },
    {
        "id": 1356039,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/deUWVEgNh2IGjShyymZhaYP40ye.jpg",
        "genres": "Action, Adventure, Thriller",
        "language": "Spanish",
        "title": "Contraataque",
        "overview": "When a hostage rescue mission creates a new enemy, Capt. Guerrero and his elite soldiers must face an ambush by a criminal group.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/38I76hGcFY6xB47pjm7pZwkfuAF.jpg",
        "releaseDate": "2025-02-27",
        "popularity": 43.4786,
        "voteAverage": 8.364,
        "voteCount": 666
    },
    {
        "id": 567,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/zZvtZZXRnZ4Tdcs0QEWaZZcIWy8.jpg",
        "genres": "Thriller, Mystery",
        "language": "English",
        "title": "Rear Window",
        "overview": "A wheelchair-bound photographer spies on his neighbors from his apartment window and becomes convinced one of them has committed murder.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/ILVF0eJxHMddjxeQhswFtpMtqx.jpg",
        "releaseDate": "1954-08-01",
        "popularity": 5.693,
        "voteAverage": 8.353,
        "voteCount": 6680
    },
    {
        "id": 274,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/aYcnDyLMnpKce1FOYUpZrXtgUye.jpg",
        "genres": "Crime, Drama, Thriller",
        "language": "English",
        "title": "The Silence of the Lambs",
        "overview": "Clarice Starling is a top student at the FBI's training academy.  Jack Crawford wants Clarice to interview Dr. Hannibal Lecter, a brilliant psychiatrist who is also a violent psychopath, serving life behind bars for various acts of murder and cannibalism.  Crawford believes that Lecter may have insight into a case and that Starling, as an attractive young woman, may be just the bait to draw him out.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg",
        "releaseDate": "1991-02-14",
        "popularity": 3.631,
        "voteAverage": 8.346,
        "voteCount": 16789
    },
    {
        "id": 770156,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/7KR1nKGaYqPuFBnqP7XBIX0DZlR.jpg",
        "genres": "Drama, Family",
        "language": "English",
        "title": "Lucy Shimmers and the Prince of Peace",
        "overview": "Second chances start when a hardened criminal crosses paths with a precocious little girl who is helped by an angel to change hearts during the holiday season.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/yfnJ5qIYx7q33fY4jqv9Pu95RSg.jpg",
        "releaseDate": "2020-10-19",
        "popularity": 3.6166,
        "voteAverage": 8.3,
        "voteCount": 304
    },
    {
        "id": 620249,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/aVFx1VtlOxR3v0ADEatalXOvwbu.jpg",
        "genres": "Animation, Fantasy, Action",
        "language": "Mandarin",
        "title": "罗小黑战记",
        "overview": "When cat spirit Luo Xiaohei's home is deforested by humans, he must find a new one. He runs into a group of other spirit creatures who take him under their wing with dreams of reconquering the land they say is rightfully theirs. However, they run into a human known as Wuxian who separates Luo Xiaohei from the other spirits and the two go on a journey, with the cat spirit learning to control his abilities as well as forming his own thoughts on whether or not he should ally with the spirits or the humans.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/aLv87NgRJUPkQ6sVLP72IisDdt4.jpg",
        "releaseDate": "2019-08-27",
        "popularity": 2.2543,
        "voteAverage": 8.3,
        "voteCount": 384
    },
    {
        "id": 569094,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/kVd3a9YeLGkoeR50jGEXM6EqseS.jpg",
        "genres": "Animation, Action, Adventure, Science Fiction",
        "language": "English",
        "title": "Spider-Man: Across the Spider-Verse",
        "overview": "After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
        "releaseDate": "2023-05-31",
        "popularity": 33.8754,
        "voteAverage": 8.342,
        "voteCount": 7535
    },
    {
        "id": 12493,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/adkWjKeklbfVIw9y2KKPSCwZl9N.jpg",
        "genres": "Drama, Crime, Mystery, Thriller",
        "language": "Japanese",
        "title": "天国と地獄",
        "overview": "In the midst of an attempt to take over his company, a powerhouse executive is hit with a huge ransom demand when his chauffeur's son is kidnapped by mistake.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/tgNjemQPG96uIezpiUiXFcer5ga.jpg",
        "releaseDate": "1963-03-01",
        "popularity": 2.9067,
        "voteAverage": 8.342,
        "voteCount": 969
    },
    {
        "id": 73,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/9LSsSPbP715XT9B7acIZzantPyX.jpg",
        "genres": "Drama",
        "language": "English",
        "title": "American History X",
        "overview": "Derek Vineyard is paroled after serving 3 years in prison for killing two African-American men. Through his brother, Danny Vineyard's narration, we learn that before going to prison, Derek was a skinhead and the leader of a violent white supremacist gang that committed acts of racial crime throughout L.A. and his actions greatly influenced Danny. Reformed and fresh out of prison, Derek severs contact with the gang and becomes determined to keep Danny from going down the same violent path as he did.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/euypWkaYFOLW3e5rLIcTAjWnhhT.jpg",
        "releaseDate": "1998-07-01",
        "popularity": 10.184,
        "voteAverage": 8.337,
        "voteCount": 11851
    },
    {
        "id": 372754,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/tLmyP7akYmxLwyfTEt2qyj2sOR3.jpg",
        "genres": "Romance, Animation",
        "language": "Japanese",
        "title": "同級生",
        "overview": "Rihito Sajo, an honor student with a perfect score on the entrance exam and Hikaru Kusakabe, in a band and popular among girls, would have never crossed paths. Until one day they started talking at the practice for their school’s upcoming chorus festival. After school, the two meet regularly, as Hikaru helps Rihito to improve his singing skills. While they listen to each other’s voice and harmonize, their hearts start to beat together.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/cIfRCA5wEvj9tApca4UDUagQEiM.jpg",
        "releaseDate": "2016-02-20",
        "popularity": 1.8957,
        "voteAverage": 8.3,
        "voteCount": 402
    },
    {
        "id": 128,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/gl0jzn4BupSbL2qMVeqrjKkF9Js.jpg",
        "genres": "Adventure, Fantasy, Animation",
        "language": "Japanese",
        "title": "もののけ姫",
        "overview": "Ashitaka, a prince of the disappearing Emishi people, is cursed by a demonized boar god and must journey to the west to find a cure. Along the way, he encounters San, a young human woman fighting to protect the forest, and Lady Eboshi, who is trying to destroy it. Ashitaka must find a way to bring balance to this conflict.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/cMYCDADoLKLbB83g4WnJegaZimC.jpg",
        "releaseDate": "1997-07-12",
        "popularity": 15.1738,
        "voteAverage": 8.329,
        "voteCount": 8325
    },
    {
        "id": 820067,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/gcgKSyE2iqwfKWMDZ8TJPxeIu0P.jpg",
        "genres": "Animation, Comedy, Romance",
        "language": "Japanese",
        "title": "映画 五等分の花嫁",
        "overview": "When five lovely young girls who hate studying hire part-time tutor Futaro, he guides not only their education but also their hearts. Time spent has brought them all closer, with feelings growing within the girls and Futaro. As they finish their third year of high school and their last school festival approaches, they set their sights on what’s next. Is there a future with one of them and Futaro?",
        "posterPath": "https://image.tmdb.org/t/p/w1280/sg7klpt1xwK1IJirBI9EHaqQwJ5.jpg",
        "releaseDate": "2022-05-20",
        "popularity": 3.7253,
        "voteAverage": 8.324,
        "voteCount": 409
    },
    {
        "id": 105,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/5bzPWQ2dFUl2aZKkp7ILJVVkRed.jpg",
        "genres": "Adventure, Comedy, Science Fiction",
        "language": "English",
        "title": "Back to the Future",
        "overview": "Eighties teenager Marty McFly is accidentally sent back in time to 1955, inadvertently disrupting his parents' first meeting and attracting his mother's romantic interest. Marty must repair the damage to history by rekindling his parents' romance and - with the help of his eccentric inventor friend Doc Brown - return to 1985.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/vN5B5WgYscRGcQpVhHl6p9DDTP0.jpg",
        "releaseDate": "1985-07-03",
        "popularity": 18.3741,
        "voteAverage": 8.319,
        "voteCount": 20493
    },
    {
        "id": 1184918,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/1pmXyN3sKeYoUhu5VBZiDU4BX21.jpg",
        "genres": "Animation, Science Fiction, Family",
        "language": "English",
        "title": "The Wild Robot",
        "overview": "After a shipwreck, an intelligent robot called Roz is stranded on an uninhabited island. To survive the harsh environment, Roz bonds with the island's animals and cares for an orphaned baby goose.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg",
        "releaseDate": "2024-09-12",
        "popularity": 47.179,
        "voteAverage": 8.318,
        "voteCount": 4860
    },
    {
        "id": 15804,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/djvXCedFiwbfp4HSoX3VU3WUVVm.jpg",
        "genres": "Crime, Drama, Romance",
        "language": "Mandarin",
        "title": "牯嶺街少年殺人事件",
        "overview": "A boy experiences first love, friendships and injustices growing up in 1960s Taiwan.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/3l8fOAwiN3N5n3hHnZ51eog7Zu2.jpg",
        "releaseDate": "1991-07-27",
        "popularity": 2.149,
        "voteAverage": 8.3,
        "voteCount": 336
    },
    {
        "id": 3782,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/stiGp1XzkLSYdUUEWTyQOZRkr49.jpg",
        "genres": "Drama",
        "language": "Japanese",
        "title": "生きる",
        "overview": "Kanji Watanabe is a middle-aged man who has worked in the same monotonous bureaucratic position for decades. Learning he has cancer, he starts to look for the meaning of his life.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/dgNTS4EQDDVfkzJI5msKuHu2Ei3.jpg",
        "releaseDate": "1952-10-09",
        "popularity": 3.4564,
        "voteAverage": 8.313,
        "voteCount": 1198
    },
    {
        "id": 10494,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/1YRtgjLb5xxUb2rsNRnr54Oc0B2.jpg",
        "genres": "Animation, Thriller",
        "language": "Japanese",
        "title": "PERFECT BLUE",
        "overview": "Encouraged by her managers, rising pop star Mima takes on a recurring role on a popular TV show, when suddenly her handlers and collaborators begin turning up murdered.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/6WTiOCfDPP8XV4jqfloiVWf7KHq.jpg",
        "releaseDate": "1998-02-28",
        "popularity": 5.9102,
        "voteAverage": 8.3,
        "voteCount": 2802
    },
    {
        "id": 207,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/hpzQHv8cA7j2Dn2CphOFYmllXzj.jpg",
        "genres": "Drama",
        "language": "English",
        "title": "Dead Poets Society",
        "overview": "At an elite, old-fashioned boarding school in New England, a passionate English teacher inspires his students to rebel against convention and seize the potential of every day, courting the disdain of the stern headmaster.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/erzbMlcNHOdx24AXOcn2ZKA7R1q.jpg",
        "releaseDate": "1989-06-02",
        "popularity": 10.2518,
        "voteAverage": 8.302,
        "voteCount": 11635
    },
    {
        "id": 101,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/bguFhzIGpQdGQ6uizm07oMKbgHi.jpg",
        "genres": "Crime, Drama, Action",
        "language": "French",
        "title": "Léon",
        "overview": "Léon, the top hit man in New York, has earned a rep as an effective \"cleaner\". But when his next-door neighbors are wiped out by a loose-cannon DEA agent, he becomes the unwilling custodian of 12-year-old Mathilda. Before long, Mathilda's thoughts turn to revenge, and she considers following in Léon's footsteps.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/yI6X2cCM5YPJtxMhUd3dPGqDAhw.jpg",
        "releaseDate": "1994-09-14",
        "popularity": 13.4959,
        "voteAverage": 8.301,
        "voteCount": 15183
    },
    {
        "id": 652837,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/i1GT0e6Crg6UezT3ibXnMS3pBAd.jpg",
        "genres": "Animation, Drama, Romance",
        "language": "Japanese",
        "title": "ジョゼと虎と魚たち",
        "overview": "With dreams of diving abroad, Tsuneo gets a job assisting Josee, an artist whose imagination takes her far beyond her wheelchair. But when the tide turns against them, they push each other to places they never thought possible, and inspire a love fit for a storybook.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/lNpZWdXC4HtXQ8nVo21gg7T9D6N.jpg",
        "releaseDate": "2020-12-25",
        "popularity": 3.7395,
        "voteAverage": 8.299,
        "voteCount": 501
    },
    {
        "id": 914,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/c8Pi8F1FzpNebtgXcSjC9nWCdSW.jpg",
        "genres": "Comedy, War",
        "language": "English",
        "title": "The Great Dictator",
        "overview": "Dictator Adenoid Hynkel tries to expand his empire while a poor Jewish barber tries to avoid persecution from Hynkel's regime.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/nhMXB8GTdswYMCL9nepDZymJCOr.jpg",
        "releaseDate": "1940-10-15",
        "popularity": 3.4312,
        "voteAverage": 8.298,
        "voteCount": 3448
    },
    {
        "id": 599,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/p47ihFj4A7EpBjmPHdTj4ipyq1S.jpg",
        "genres": "Drama",
        "language": "English",
        "title": "Sunset Boulevard",
        "overview": "A hack screenwriter writes a screenplay for a former silent film star who has faded into Hollywood obscurity.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/sC4Dpmn87oz9AuxZ15Lmip0Ftgr.jpg",
        "releaseDate": "1950-08-10",
        "popularity": 3.9607,
        "voteAverage": 8.295,
        "voteCount": 2674
    },
    {
        "id": 644479,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/1fOsyhVz5qyX2rl1qqX6KImVhTx.jpg",
        "genres": "Drama, Comedy",
        "language": "Spanish",
        "title": "Dedicada A Mi Ex",
        "overview": "The film tells the story of Ariel, a 21-year-old who decides to form a rock band to compete for a prize of ten thousand dollars in a musical band contest, this as a last option when trying to get money to save their relationship and reunite with his ex-girlfriend, which breaks due to the trip she must make to Finland for an internship. Ariel with her friend Ortega, decides to make a casting to find the other members of the band, although they do not know nothing about music, thus forming a band with members that have diverse and opposite personalities.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/xc4bTXVwYNXi10jG9dwcaYt5IpU.jpg",
        "releaseDate": "2019-11-01",
        "popularity": 0.8238,
        "voteAverage": 8.292,
        "voteCount": 506
    },
    {
        "id": 1139087,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/hUeSuUxNyQivx2wrRvGoyZiZDUu.jpg",
        "genres": "Animation, Family, Fantasy, Comedy",
        "language": "English",
        "title": "Once Upon a Studio",
        "overview": "Created for Disney's 100th anniversary, the short features Mickey Mouse corralling a gallery of legendary Disney characters for a group photo.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/aiy3G1cYWV3LgKZHY6a3jL8bjYL.jpg",
        "releaseDate": "2023-09-24",
        "popularity": 3.3403,
        "voteAverage": 8.285,
        "voteCount": 382
    },
    {
        "id": 18491,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/xLMJCCSatxENpHO9rLW9yD8A12C.jpg",
        "genres": "Animation, Science Fiction, Action, Drama",
        "language": "Japanese",
        "title": "新世紀エヴァンゲリオン劇場版 Air／まごころを、君に",
        "overview": "SEELE orders an all-out attack on NERV, aiming to destroy the Evas before Gendo can advance his own plans for the Human Instrumentality Project. Shinji is pushed to the limits of his sanity as he is forced to decide the fate of humanity.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/j6G24dqI4WgUtChhWjfnI4lnmiK.jpg",
        "releaseDate": "1997-07-19",
        "popularity": 6.4036,
        "voteAverage": 8.3,
        "voteCount": 1675
    },
    {
        "id": 3082,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/kSlO1pHpwQfPQdgVPr7dJiJNtJ8.jpg",
        "genres": "Comedy, Drama, Romance",
        "language": "English",
        "title": "Modern Times",
        "overview": "A bumbling tramp desires to build a home with a young woman, yet is thwarted time and time again by his lack of experience and habit of being in the wrong place at the wrong time..",
        "posterPath": "https://image.tmdb.org/t/p/w1280/7uoiKOEjxBBW0AgDGQWrlfGQ90w.jpg",
        "releaseDate": "1936-02-05",
        "popularity": 3.588,
        "voteAverage": 8.282,
        "voteCount": 3795
    },
    {
        "id": 335,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/26SUDI2iKhZTIKcU4ZzezTH1G15.jpg",
        "genres": "Drama, Western",
        "language": "Italian",
        "title": "C'era una volta il West",
        "overview": "As the railroad builders advance unstoppably through the Arizona desert on their way to the sea, Jill arrives in the small town of Flagstone with the intention of starting a new life.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/qbYgqOczabWNn2XKwgMtVrntD6P.jpg",
        "releaseDate": "1968-12-21",
        "popularity": 37.7145,
        "voteAverage": 8.281,
        "voteCount": 4513
    },
    {
        "id": 42269,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/2Kkqmy3EpXqBDqv1vvsNXX3pwww.jpg",
        "genres": "Drama, Comedy",
        "language": "Italian",
        "title": "C'eravamo tanto amati",
        "overview": "Three partisans bound by a strong friendship return home after the war, but the clash with everyday reality puts a strain on their bond.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/zGGWYpiKNwjpKxelPxOMqJnUgDs.jpg",
        "releaseDate": "1974-12-21",
        "popularity": 1.2938,
        "voteAverage": 8.279,
        "voteCount": 591
    },
    {
        "id": 92321,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/qknxyRgP6UTmwJ4B9tDAmzHMq7u.jpg",
        "genres": "Romance, Animation, Fantasy",
        "language": "Japanese",
        "title": "蛍火の杜へ",
        "overview": "One hot summer day a little girl gets lost in an enchanted forest of the mountain god where spirits reside. A young boy appears before her, but she cannot touch him for fear of making him disappear. And so a wondrous adventure awaits...",
        "posterPath": "https://image.tmdb.org/t/p/w1280/mDqzHV8UXWWNpZkoAbKmKX1ZxEE.jpg",
        "releaseDate": "2011-09-17",
        "popularity": 0.0034,
        "voteAverage": 8.278,
        "voteCount": 1143
    },
    {
        "id": 1585,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/3q35nBLCIdEbxYfsr7D5ocYQXKz.jpg",
        "genres": "Drama, Family, Fantasy",
        "language": "English",
        "title": "It's a Wonderful Life",
        "overview": "A holiday favourite for generations...  George Bailey has spent his entire life giving to the people of Bedford Falls.  All that prevents rich skinflint Mr. Potter from taking over the entire town is George's modest building and loan company.  But on Christmas Eve the business's $8,000 is lost and George's troubles begin.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/bSqt9rhDZx1Q7UZ86dBPKdNomp2.jpg",
        "releaseDate": "1946-12-20",
        "popularity": 21.2011,
        "voteAverage": 8.277,
        "voteCount": 4487
    },
    {
        "id": 632632,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/9Xz0bzUFTVgDZd4WZz1cJDQjLkB.jpg",
        "genres": "Animation, Drama, Music, Romance",
        "language": "Japanese",
        "title": "映画 ギヴン",
        "overview": "Haruki secretly had feelings for Akihiko for years, but Akihiko was still in a relationship with his roommate, the violinist Ugetsu Murata. Haruki, Akihiko, and Ugetsu's love clashes and starts to move forward.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/pegCub2zdYD5As43AOmGsIctuKc.jpg",
        "releaseDate": "2020-08-22",
        "popularity": 3.1161,
        "voteAverage": 8.3,
        "voteCount": 400
    },
    {
        "id": 533514,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/aLqtWLA6NQHBwQHvHDq5z4EKUm0.jpg",
        "genres": "Animation, Fantasy, Romance, Drama",
        "language": "Japanese",
        "title": "劇場版 ヴァイオレット・エヴァーガーデン",
        "overview": "As the world moves on from the war and technological advances bring changes to her life, Violet still hopes to see her lost commanding officer again.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/A9R6bukzzRmOzxvDQsXdQpeNm8l.jpg",
        "releaseDate": "2020-09-18",
        "popularity": 4.6811,
        "voteAverage": 8.3,
        "voteCount": 442
    },
    {
        "id": 77338,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/oDTHNGAH1gZwNk45do1rOoU3oxN.jpg",
        "genres": "Drama, Comedy",
        "language": "French",
        "title": "Intouchables",
        "overview": "A true story of two men who should never have met – a quadriplegic aristocrat who was injured in a paragliding accident and a young man from the projects.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/1QU7HKgsQbGpzsJbJK4pAVQV9F5.jpg",
        "releaseDate": "2011-11-02",
        "popularity": 14.4002,
        "voteAverage": 8.3,
        "voteCount": 17590
    },
    {
        "id": 28,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/9Qs9oyn4iE8QtQjGZ0Hp2WyYNXT.jpg",
        "genres": "Drama, War",
        "language": "English",
        "title": "Apocalypse Now",
        "overview": "At the height of the Vietnam war, Captain Benjamin Willard is sent on a dangerous mission that, officially, \"does not exist, nor will it ever exist.\" His goal is to locate - and eliminate - a mysterious Green Beret Colonel named Walter Kurtz, who has been leading his personal army on illegal guerrilla missions into enemy territory.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/gQB8Y5RCMkv2zwzFHbUJX3kAhvA.jpg",
        "releaseDate": "1979-05-19",
        "popularity": 9.7228,
        "voteAverage": 8.271,
        "voteCount": 8478
    },
    {
        "id": 901,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/Ma7mQsldFCaQpsZbm8zolgLfmV.jpg",
        "genres": "Comedy, Drama, Romance",
        "language": "English",
        "title": "City Lights",
        "overview": "A tramp falls in love with a beautiful blind flower girl. His on-and-off friendship with a wealthy man allows him to be the girl's benefactor and suitor.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/ugmakEL5y294I5bXgiBqApuZpwc.jpg",
        "releaseDate": "1931-02-06",
        "popularity": 2.4471,
        "voteAverage": 8.269,
        "voteCount": 2255
    },
    {
        "id": 8587,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/wXsQvli6tWqja51pYxXNG1LFIGV.jpg",
        "genres": "Family, Animation, Drama",
        "language": "English",
        "title": "The Lion King",
        "overview": "Young lion prince Simba, eager to one day become king of the Pride Lands, grows up under the watchful eye of his father Mufasa; all the while his villainous uncle Scar conspires to take the throne for himself. Amid betrayal and tragedy, Simba must confront his past and find his rightful place in the Circle of Life.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg",
        "releaseDate": "1994-06-15",
        "popularity": 20.7057,
        "voteAverage": 8.3,
        "voteCount": 18728
    },
    {
        "id": 637920,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/inEy3A5OPgeYW4rjRiGycfEeQzA.jpg",
        "genres": "Drama",
        "language": "Turkish",
        "title": "7. Koğuştaki Mucize",
        "overview": "Separated from his daughter, a father with an intellectual disability must prove his innocence when he is jailed for the death of a commander's child.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/bOth4QmNyEkalwahfPCfiXjNh1r.jpg",
        "releaseDate": "2019-10-10",
        "popularity": 4.8765,
        "voteAverage": 8.257,
        "voteCount": 4452
    },
    {
        "id": 975,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/354kfjVb96mtFALMhBE6jzHGiA2.jpg",
        "genres": "War, Drama, History",
        "language": "English",
        "title": "Paths of Glory",
        "overview": "A commanding officer defends three scapegoats on trial for a failed offensive that occurred within the French Army in 1916.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/tJXwtzOSNUC8dxJfrdvkNtGrrgW.jpg",
        "releaseDate": "1957-10-25",
        "popularity": 4.0368,
        "voteAverage": 8.257,
        "voteCount": 3018
    },
    {
        "id": 10376,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/muSeX7fnNw0pv4zHK7RSwZln6Hk.jpg",
        "genres": "Drama, Music",
        "language": "Italian",
        "title": "La leggenda del pianista sull'oceano",
        "overview": "The story of a virtuoso piano player who lives his entire life aboard an ocean liner. Born and raised on the ship, 1900 learned about the outside world through interactions with passengers, never setting foot on land, even for the love of his life. Years later, the ship may be destroyed, and a former band member fears that 1900 may still be aboard, willing to go down with the ship.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/iOcbJ5pxokOPDRgieVDbsFMrCc6.jpg",
        "releaseDate": "1998-10-28",
        "popularity": 2.8642,
        "voteAverage": 8.255,
        "voteCount": 2302
    },
    {
        "id": 670,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/sdwjQEM869JFwMytTmvr6ggvaUl.jpg",
        "genres": "Drama, Thriller, Mystery, Action",
        "language": "Korean",
        "title": "올드보이",
        "overview": "With no clue how he came to be imprisoned, drugged and tortured for 15 years, a desperate man seeks revenge on his captors.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/pWDtjs568ZfOTMbURQBYuT4Qxka.jpg",
        "releaseDate": "2003-11-21",
        "popularity": 16.1307,
        "voteAverage": 8.3,
        "voteCount": 8993
    },
    {
        "id": 630566,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/L7DIiAdP8DnNqOh7454ZrTYspR.jpg",
        "genres": "Music, Drama, Romance",
        "language": "English",
        "title": "Clouds",
        "overview": "Young musician Zach Sobiech discovers his cancer has spread, leaving him just a few months to live. With limited time, he follows his dream and makes an album, unaware that it will soon be a viral music phenomenon.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/d0OdD1I8qAfETvE9Rp9Voq7R8LR.jpg",
        "releaseDate": "2020-10-09",
        "popularity": 1.759,
        "voteAverage": 8.25,
        "voteCount": 1017
    },
    {
        "id": 29259,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/f72GEQF2lKsdmEULSI9bWCbQylH.jpg",
        "genres": "Drama, Thriller, Crime",
        "language": "French",
        "title": "Le Trou",
        "overview": "Four prison inmates have been hatching a plan to literally dig out of jail when another prisoner, Claude Gaspard, is moved into their cell. They take a risk and share their plan with the newcomer. Over the course of three days, the prisoners and friends break through the concrete floor using a bed post and begin to make their way through the sewer system -- yet their escape is anything but assured.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/xyZhiOz5NHVBUKlpioxjwajy7pm.jpg",
        "releaseDate": "1960-03-18",
        "popularity": 1.7226,
        "voteAverage": 8.2,
        "voteCount": 503
    },
    {
        "id": 568332,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/ySaK6hpbCc2OE13ac7ovhgWwR5u.jpg",
        "genres": "Music",
        "language": "English",
        "title": "Taylor Swift: Reputation Stadium Tour",
        "overview": "Taylor Swift takes the stage in Dallas for the Reputation Stadium Tour and celebrates a monumental night of music, memories and visual magic.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/u6oXUTtOuJRPdUgUuPAVVJPSKCo.jpg",
        "releaseDate": "2018-12-31",
        "popularity": 1.1847,
        "voteAverage": 8.244,
        "voteCount": 401
    },
    {
        "id": 572154,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/5MgMCnslrxQfOfaq6T5ndkLlcCk.jpg",
        "genres": "Animation, Romance, Drama, Fantasy",
        "language": "Japanese",
        "title": "青春ブタ野郎はゆめみる少女の夢を見ない",
        "overview": "In Fujisawa, Sakuta Azusagawa is in his second year of high school. Blissful days with his girlfriend and upperclassman, Mai Sakurajima, are interrupted by the appearance of his first crush, Shoko Makinohara.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/AtFnN4OztDJy8IFwYd5JfU0jlEM.jpg",
        "releaseDate": "2019-06-15",
        "popularity": 3.6288,
        "voteAverage": 8.2,
        "voteCount": 536
    },
    {
        "id": 654299,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/o33acwn7KliNpJRbjy4FrMSpiQ9.jpg",
        "genres": "Comedy, Drama, Music",
        "language": "Spanish",
        "title": "Como caído del cielo",
        "overview": "Returning to Earth as an imitator, the legendary Mexican artist Pedro Infante must prove that he is no longer a womanizer to enter paradise.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/xg6QZdlHrq2dtSK8cfnQQMnmpeY.jpg",
        "releaseDate": "2019-12-24",
        "popularity": 1.1068,
        "voteAverage": 8.241,
        "voteCount": 357
    },
    {
        "id": 447362,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/u6aGN71Hx39iX8Uv4ILRRKHmAXc.jpg",
        "genres": "Drama, Romance",
        "language": "English",
        "title": "Life in a Year",
        "overview": "A 17 year old finds out that his girlfriend is dying, so he sets out to give her an entire life, in the last year she has left.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/bP7u19opmHXYeTCUwGjlLldmUMc.jpg",
        "releaseDate": "2020-11-27",
        "popularity": 4.0092,
        "voteAverage": 8.242,
        "voteCount": 1912
    },
    {
        "id": 504253,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/YLyORLsYIjC0d1TFBSpJKk7piP.jpg",
        "genres": "Animation, Drama, Romance",
        "language": "Japanese",
        "title": "君の膵臓をたべたい",
        "overview": "After his classmate and crush is diagnosed with a pancreatic disease, an average high schooler sets out to make the most of her final days.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/qDWA7fB4cZ4sBP6YgwlxvraDHi7.jpg",
        "releaseDate": "2018-09-01",
        "popularity": 6.1918,
        "voteAverage": 8.24,
        "voteCount": 1611
    },
    {
        "id": 527641,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/27ZkYMWynuK2qiDP6awc3MsCaOs.jpg",
        "genres": "Romance, Drama",
        "language": "English",
        "title": "Five Feet Apart",
        "overview": "Seventeen-year-old Stella spends most of her time in the hospital as a cystic fibrosis patient. Her life is full of routines, boundaries and self-control — all of which get put to the test when she meets Will, an impossibly charming teen who has the same illness. There's an instant flirtation, though restrictions dictate that they must maintain a safe distance between them. As their connection intensifies, so does the temptation to throw the rules out the window and embrace that attraction.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/kreTuJBkUjVWePRfhHZuYfhNE1T.jpg",
        "releaseDate": "2019-03-14",
        "popularity": 8.1524,
        "voteAverage": 8.239,
        "voteCount": 5711
    },
    {
        "id": 995133,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/wO0MIGcA7w7tBI9Ey80Q4Z7qnPm.jpg",
        "genres": "Animation, Family, Adventure, Fantasy",
        "language": "English",
        "title": "The Boy, the Mole, the Fox and the Horse",
        "overview": "The unlikely friendship of a boy, a mole, a fox and a horse traveling together in the boy's search for home.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/aBBJRyS17TIrdXih3uSYvPAR3Ua.jpg",
        "releaseDate": "2022-12-25",
        "popularity": 3.9472,
        "voteAverage": 8.238,
        "voteCount": 625
    },
    {
        "id": 508965,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/mlxKite1x1PgmIhJgAxNS9eHmH8.jpg",
        "genres": "Animation, Family, Adventure, Comedy, Fantasy",
        "language": "English",
        "title": "Klaus",
        "overview": "When Jesper distinguishes himself as the Postal Academy's worst student, he is sent to Smeerensburg, a small village located on an icy island above the Arctic Circle, where grumpy inhabitants barely exchange words, let alone letters. Jesper is about to give up and abandon his duty as a postman when he meets local teacher Alva and Klaus, a mysterious carpenter who lives alone in a cabin full of handmade toys.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/q125RHUDgR4gjwh1QkfYuJLYkL.jpg",
        "releaseDate": "2019-11-08",
        "popularity": 4.0994,
        "voteAverage": 8.238,
        "voteCount": 4256
    },
    {
        "id": 299534,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
        "genres": "Adventure, Science Fiction, Action",
        "language": "English",
        "title": "Avengers: Endgame",
        "overview": "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg",
        "releaseDate": "2019-04-24",
        "popularity": 24.3061,
        "voteAverage": 8.239,
        "voteCount": 26302
    },
    {
        "id": 299536,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg",
        "genres": "Adventure, Action, Science Fiction",
        "language": "English",
        "title": "Avengers: Infinity War",
        "overview": "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
        "releaseDate": "2018-04-25",
        "popularity": 34.6673,
        "voteAverage": 8.2,
        "voteCount": 30490
    },
    {
        "id": 25237,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/oIQMt3Q6Qa37YD0JOdYkrIAPYDk.jpg",
        "genres": "Drama, War",
        "language": "Russian",
        "title": "Иди и смотри",
        "overview": "The invasion of a village in Byelorussia by German forces sends young Florya into the forest to join the weary Resistance fighters, against his family's wishes. There he meets a girl, Glasha, who accompanies him back to his village. On returning home, Florya finds his family and fellow peasants massacred. His continued survival amidst the brutal debris of war becomes increasingly nightmarish, a battle between despair and hope.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/qNbMsKVzigERgJUbwf8pKyZogpb.jpg",
        "releaseDate": "1985-10-17",
        "popularity": 6.4297,
        "voteAverage": 8.237,
        "voteCount": 1586
    },
    {
        "id": 490132,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/5En0fmDagt3Pk8d7P3uTwfeQceg.jpg",
        "genres": "Drama, History",
        "language": "English",
        "title": "Green Book",
        "overview": "Tony Lip, a bouncer in 1962, is hired to drive pianist Don Shirley on a tour through the Deep South in the days when African Americans, forced to find alternate accommodations and services due to segregation laws below the Mason-Dixon Line, relied on a guide called The Negro Motorist Green Book.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/7BsvSuDQuoqhWmU2fL7W2GOcZHU.jpg",
        "releaseDate": "2018-11-16",
        "popularity": 15.7456,
        "voteAverage": 8.232,
        "voteCount": 11986
    },
    {
        "id": 283566,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/1EAxNqdkVnp48a7NUuNBHGflowM.jpg",
        "genres": "Animation, Action, Science Fiction, Drama",
        "language": "Japanese",
        "title": "シン・エヴァンゲリオン劇場版:||",
        "overview": "In the aftermath of the Fourth Impact, stranded without their Evangelions, Shinji, Asuka and Rei find refuge in one of the rare pockets of humanity that still exist on the ruined planet Earth. There, each lives a life far different from their days as an Evangelion pilot. However, the danger to the world is far from over. A new impact is looming on the horizon—one that will prove to be the true end of Evangelion.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/md5wZRRj8biHrGtyitgBZo7674t.jpg",
        "releaseDate": "2021-03-08",
        "popularity": 4.2579,
        "voteAverage": 8.231,
        "voteCount": 847
    },
    {
        "id": 265177,
        "isAdult": false,
        "backdropImage": "https://image.tmdb.org/t/p/w1280/hb1GBVDwQIvSNpx1cQUFAIHfyBW.jpg",
        "genres": "Drama",
        "language": "French",
        "title": "Mommy",
        "overview": "A peculiar neighbor offers hope to a recent widow who is struggling to raise a teenager who is unpredictable and, sometimes, violent.",
        "posterPath": "https://image.tmdb.org/t/p/w1280/3zyQtPg3avKprmJP2gBiYgyWUQC.jpg",
        "releaseDate": "2014-09-19",
        "popularity": 2.9866,
        "voteAverage": 8.2,
        "voteCount": 2753
    }
]